## Automatically generated by gen-lists-of-programs.sh.  DO NOT EDIT BY HAND!
no_install__progs =
no_install__progs += src/arch
no_install__progs += src/coreutils
no_install__progs += src/hostname
build_if_possible__progs =
default__progs =
default__progs += src/echox
